# Site settings
title: Chefter, Inc
email: contact@chefter.com
description: >
  Chefter connects you to our professional chefs for real time support when It counts the most. Our chefs see what you show them using your smart phone camera. It’s like having a chef right on your shoulder, helping you every step of the way.
baseurl: ""
url: http://blog.chefter.com

gems: [jekyll-paginate]
paginate: 3
paginate_path: "blog/page:num/"
markdown: kramdown

prose:
  siteurl: "http://blog.chefter.com"
  media: "img"